name: pipeline-integracion-continua-mtrr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verificar-servidor:
    runs-on: ubuntu-latest

    steps:
    - name: Copiar codigo fuente
      uses: actions/checkout@v4

    - name: Configurar entorno de Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalar dependencias (node_modules)
      run: npm install

    - name: Verificar arranque limpio del servidor Express
      run: |
        echo "Iniciando prueba sintáctica del servidor..."
        node -e "
          try {
            require('./src/index.js');
            console.log('✅ El servidor Express compila perfectamente sin errores.');
            process.exit(0);
          } catch (error) {
            console.error('❌ Error crítico detectado en el backend:', error.message);
            process.exit(1);
          }
        "