name: pipeline-integracion-continua-mtrr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verificar-servidor:
    runs-on: ubuntu-latest

    steps:
    - name: Copiar codigo fuente
      uses: actions/checkout@v4

    # AQUÍ ESTÁ LA CORRECCIÓN: Cambiamos 'with-node' por 'setup-node'
    - name: Configurar entorno de Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalar dependencias (node_modules)
      run: |
        if [ -f package.json ]; then
          npm install
        else
          echo "package.json no encontrado, saltando instalación..."
        fi

    - name: Verificar errores sintacticos en el Backend
      run: |
        echo "Iniciando inspección sintáctica en el ecosistema Express..."
        node --check ./index.js
        echo "✅ El archivo principal no contiene errores léxicos ni sintácticos estructurales."